    dw DarkAmpharosCard
	dw DarkCrobatCard
	dw DarkDonphanCard
    dw DarkEspeonCard
    dw DarkFeraligatrCard
    dw DarkGengarCard
    dw DarkHoundoomCard
    dw DarkPorygonTwoCard
    dw DarkScizorCard
    dw DarkTyphlosionCard
    dw DarkTyranitarCard
    dw LightArcanineCard
    dw LightAzumarillCard
    dw LightDragoniteCard
    dw LightTogeticCard
    dw MiracleEnergyCard
    dw DarkAriadosCard
    dw DarkOmastarCard
    dw DarkSlowkingCard
    dw DarkUrsaringCard
    dw LightDragonairCard
    dw LightLanturnCard
    dw LightLedianCard
    dw LightMachampCard
    dw LightPiloswineCard
    dw Chansey2Card
    dw DarkCroconawCard
    dw DarkExeggutorCard
    dw DarkFlaaffyCard
    dw DarkForretressCard
    dw DarkHaunterCard
    dw DarkOmanyteCard
    dw DarkPupitarCard
    dw DarkQuilavaCard
    dw DarkWigglytuffCard
    dw Heracross2Card
    dw Hitmonlee2Card
    dw Houndour3Card
    dw Jigglypuff2Card
    dw LightDewgongCard
    dw LightFlareonCard
    dw LightGolduckCard
    dw LightJolteonCard
    dw LightMachokeCard
    dw LightNinetalesCard
    dw LightSlowbroCard
    dw LightVaporeonCard
    dw LightVenomothCard
    dw LightWigglytuffCard
    dw Scyther2Card
    dw Togepi2Card
    dw Cyndaquil3Card
    dw DarkOctilleryCard
    dw Dratini1Card
    dw Exeggcute2Card
    dw GastlyCard2
    dw Girafarig2Card
    dw Gligar2Card
    dw Growlithe2Card
    dw Hitmonchan2Card
    dw Larvitar2Card
    dw Ledyba2Card
    dw LightSunfloraCard
    dw Machop2Card
    dw Mantine2Card
    dw Mareep3Card
    dw Phanpy2card
    dw Pineco2Card
    dw Porygon2Card
    dw Psyduck2Card
    dw Remoraid2Card
    dw Seel2Card
    dw Slugma2Card
    dw Sunkern2Card
    dw Swinub3Card
    dw Totodile3Card
    dw Venonat2Card
    dw Vulpix2Card
    dw BrokenGroundGymCard
    dw EXPALLCard
    dw ImpostorProfessorOaksInventionCard
    dw RadioTowerCard
    dw ThoughtWaveMachineCard
    dw CounterattackClawsCard
    dw EnergyAmplifierCard
    dw EnergyStadiumCard
    dw LuckyStadiumCard
    dw MagnifierCard
    dw PokemonPersonalityTestCard
    dw TeamRocketsEvilDeedsCard
    dw HealPowderCard
    dw MailFromBillCard
    dw ShiningCelebiCard
    dw ShiningCharizardCard
    dw ShiningKabutopsCard
    dw ShiningMewtwoCard
    dw ShiningNoctowlCard
    dw ShiningRaichuCard
    dw ShiningSteelixCard
    dw ShiningTyranitarCard